### ISSUE TITLE
Bug: archive is engine

### ISSUE THREAD

**Issue by fleurc** [paulgoio/searxng#20]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 1.0.0

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 100
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi @fleurc ,
I tested out the engine. If you check out this example request that SearXNG does when using archive is: https://archive.is/search/?q=time you can see that the engine is sitting behind cloudflare, which is blocking access to the site on my public instance. As with startpage there is nothing really I can do about this; Closing.
