### ISSUE TITLE
Bug: 1x engine

### ISSUE THREAD

**Issue by fleurc** [paulgoio/searxng#21]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 1.0.0

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineXPathException
  * Percentage: 100
  * Parameters: `('//searchresult', 'index 0 not found')`
  * File name: `searx/engines/www1x.py:41`
  * Function: `response`
  * Code: `xmlsearchresult = eval_xpath_getindex(xmldom, '//searchresult', 0)`

**Comment by tiekoetter** [comment]
@fleurc Could you try https://github.com/tiekoetter/searxng/tree/fix-1x ?

**Comment by tiekoetter** [comment]
This is closed in https://github.com/searxng/searxng/pull/845

**Comment by mrpaulblack** [comment]
Thanks for fixing the engine upstream @tiekoetter :D

I pushed the changes from upstream to my fork and it works perfectly (sorry for not testing before...) Fixed in 2b5bb9a8296a3fed783ab17828f0a2bcbc62a065; Closing. :+1:
