### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by HLShls123** [paulgoio/searxng#24]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 1.0.0

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 70
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:123`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 0
  * Parameters: `('API error::q must be longer than or equal to 1 characters',)`
  * File name: `searx/engines/qwant.py:123`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: json.decoder.JSONDecodeError
  * Percentage: 0
  * Parameters: `('Expecting value',)`
  * File name: `searx/engines/qwant.py:110`
  * Function: `response`
  * Code: `search_results = loads(resp.text)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'api.qwant.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi @HLShls123 ,
Thanks for the issue. Qwant seems break since yesterday on my instance and I am not really sure why yet. Looking at other instances they work fine: https://searx.tiekoetter.com/search?q=%21qwant+time&category_general=on&language=en-US&time_range=&safesearch=0&theme=simple

So I am guessing they blocked my instance or something!?

here is the exception log from my instance:
```
2022-02-04 11:09:52,579 WARNING:searx.engines.qwant: ErrorContext('searx/engines/qwant.py', 123, "raise SearxEngineAPIException('API error::' + msg)", 'searx.exceptions.SearxEngineAPIException', None, ('API error::unknown',)) False
2022-02-04 11:09:52,580 ERROR:searx.engines.qwant: exception : API error::unknown
Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/online.py", line 143, in search
    search_results = self._search_basic(query, params)
  File "/usr/local/searxng/searx/search/processors/online.py", line 131, in _search_basic
    return self.engine.response(response)
  File "/usr/local/searxng/searx/engines/qwant.py", line 123, in response
    raise SearxEngineAPIException('API error::' + msg)
searx.exceptions.SearxEngineAPIException: API error::unknown
```

I will keep this ticket open and update if a fix is found...

**Comment by mrpaulblack** [comment]
Qwant is not blocking nor rate limiting my public instances IP for 3 days now; Closing (For now, going to reopen if this happens again).
