### ISSUE TITLE
Bug: apk mirror engine

### ISSUE THREAD

**Issue by SSVUSDNHL** [paulgoio/searxng#35]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 2022.04.02-765504ce

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

**Comment by mrpaulblack** [comment]
Hi @SSVUSDNHL,
your bug report template is empty and apk mirror works just fine on my paulgo instance; Closing (you can test by searching for `!apkm time`).
