### ISSUE TITLE
How do I host this on Heroku?

### ISSUE THREAD

**Issue by IdleEndeavor** [paulgoio/searxng#36]
I really like this version of SearXNG. I'd like to host it on Heroku for myself.
Can someone explain how that can be done?

**Comment by mrpaulblack** [comment]
Hi @IdleEndeavor ,
I dont use Heroku myself and are therefor not familiar with the service. We have this discussion upstream: https://github.com/searxng/searxng/issues/948 .

The only changes in my fork are some colors in the simple theme... So I would like to ask you to follow the discussion upstream (to have this all in one place).

For now I will close the ticket, but feel free to comment and reopen again :+1:
