### ISSUE TITLE
Bug: qwant engine

### ISSUE THREAD

**Issue by Cliffmode2000** [paulgoio/searxng#38]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 2022.07.01-5672f5ad

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 20
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:123`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

Error
  * Error: json.decoder.JSONDecodeError
  * Percentage: 0
  * Parameters: `('Expecting value',)`
  * File name: `searx/engines/qwant.py:110`
  * Function: `response`
  * Code: `search_results = loads(resp.text)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'api.qwant.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'api.qwant.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi @Cliffmode2000 ,
I am aware of the issue, yesterday my proxy setup broke so right now my instance is deployed without proxies -> so this is why qwant blocks my instance. I am currently working on a fix, thanks for the report :+1:

**Comment by mrpaulblack** [comment]
I fixed my proxies in 0d4c4b1c4b3210547f3daca9a5e8bce6b53d2ba4, qwant is working again; Closing.
