### ISSUE TITLE
Bug: pubmed engine

### ISSUE THREAD

**Issue by Brainhub24** [paulgoio/searxng#40]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 2022.07.02-4ef62637

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ConnectError
  * Percentage: 100
  * Parameters: `(None, None, 'eutils.ncbi.nlm.nih.gov')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi,
sorry for the long delay. I check again and pubmed is working now: https://paulgo.io/search?q=%21pubmed%20time&language=en-US&time_range=None&safesearch=1&categories=none ; Closing.
