### ISSUE TITLE
Bug: google images engine

### ISSUE THREAD

**Issue by iblowmymind** [paulgoio/searxng#41]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 2022.07.08-a1e8af07

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineXPathException
  * Percentage: 100
  * Parameters: `('//script[contains(., "AF_initDataCallback({key: ")]', 'index 1 not found')`
  * File name: `searx/engines/google_images.py:107`
  * Function: `parse_urls_img_from_js`
  * Code: `img_src_script = eval_xpath_getindex(dom, '//script[contains(., "AF_initDataCallback({key: ")]', 1).text`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 75
  * Parameters: `('200', 'OK', 'consent.google.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 5
  * Parameters: `('200', 'OK', 'consent.google.ru')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 5
  * Parameters: `('200', 'OK', 'consent.google.de')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 5
  * Parameters: `('200', 'OK', 'consent.google.co.uk')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 0
  * Parameters: `('200', 'OK', 'consent.google.com.br')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 0
  * Parameters: `('200', 'OK', 'consent.google.ca')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 0
  * Parameters: `('200', 'OK', 'consent.google.sk')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 0
  * Parameters: `('200', 'OK', 'consent.google.ee')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`
  
*(just goes on like this, had to remove because the issue wouldn't be autocreated (too long body on issue creation request))*

**Comment by mrpaulblack** [comment]
Hi @iblowmymind ,
It looks like my instance is not the only one having this issue: Here is the issue upstream. Work will be tracked there: https://github.com/searxng/searxng/issues/1432

**Comment by iblowmymind** [comment]
Oh, thanks for informing!

**Comment by iblowmymind** [comment]
Closing as it's fixed and upstream was merged.
