### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by iblowmymind** [paulgoio/searxng#42]
No "official" report for this, as the official stats page states that Google search works okay.
However, no google results are shown in a search:
![image](https://user-images.githubusercontent.com/28228415/183578352-b3f3aec7-c074-43b2-b82f-01d364ec1c3b.png)

**Comment by mrpaulblack** [comment]
Hi,
I added the upsrteam fix for this in 2718b24a2a14ff2451f7229d1059b0c4d9d4ed15 , sorry for the delay; Closing.
