### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by iblowmymind** [paulgoio/searxng#43]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 2022.08.05-cee58602

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ProxyError
  * Percentage: 0
  * Parameters: `(None, None, 'search.brave.com')`
  * File name: `searx/search/processors/online.py:107`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 0
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:107`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi,
It seems its working for now: https://paulgo.io/search?q=%21brave%20time&language=en-US&time_range=None&safesearch=1&categories=none . I will close the issue, but if its happening again, please reopen and ping me :+1:, thanks :D ; Closing.
