### ISSUE TITLE
Bug: startpage engine

### ISSUE THREAD

**Issue by iblowmymind** [paulgoio/searxng#44]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 2022.08.05-cee58602

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 60
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: 2 redirects, maximum: 0
  * Percentage: 40
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: searx.exceptions.SearxEngineCaptchaException
  * Percentage: 0
  * Parameters: `('CAPTCHA',)`
  * File name: `searx/engines/startpage.py:66`
  * Function: `raise_captcha`
  * Code: `raise SearxEngineCaptchaException(suspended_time=7 * 24 * 3600)`

**Comment by mrpaulblack** [comment]
Hi,
Same as on the brave issue. It seems to work for now: https://paulgo.io/search?q=%21startpage%20time&language=en-US&time_range=None&safesearch=1&categories=none , but if its happening again please write a comment with a ping, thanks :D ; Closing.
