### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by Rathmox** [paulgoio/searxng#46]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 2022.10.14-1a5b0965

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi,
sorry for the late reply but duckduckgo seems to work again. I turned on the limiter again and updated to the latest upstream version -> see: https://staging.paulgo.io/search?q=%21duckduckgo%20time&language=en-US&time_range=None&safesearch=1&categories=none

;Closing.

**Comment by mrpaulblack** [comment]
Nvm my instance is still getting blocked by duckduckgo -_- ; Reopening.

**Comment by leimkhao** [comment]
I am still being denied access to duckduckgo in my environment. Other search engines also deny me from time to time, but duckduckgo is the only one that has been denying me for over a week as far as I can remember.

**Comment by mrpaulblack** [comment]
As of version `2022.12.30-647a0aa9` -> Its fixed with the update to latest upstream for now -> https://paulgo.io/search?q=%21duckduckgo%20time&language=en-US&time_range=None&safesearch=1&categories=none ; Closing.
