### ISSUE TITLE
LiveJournal spamming with Bing

### ISSUE THREAD

**Issue by MuntashirAkon** [paulgoio/searxng#49]
I'm seeing this MS spam in all queries.

![Screenshot 2022-12-31 at 17 11 59](https://user-images.githubusercontent.com/8176128/210134645-048a8080-06ca-4a43-a8d5-e16ffbc0c5cd.png)

PS: Maybe this should be opened in the main project.

**Comment by mrpaulblack** [comment]
Hi,
can you please comment with a search query where this happens? I tried https://paulgo.io/search?q=time&language=en-US&time_range=None&safesearch=1&categories=general but I dont see those results from bing in the general catergory...

**Comment by MuntashirAkon** [comment]
https://paulgo.io/search?q=jekyll%20custom%20functions&language=en-US&time_range=None&safesearch=1&categories=general

**Comment by mrpaulblack** [comment]
Hi,
Upstream the bing engine and language handeling got a major refactor. When using your link [search query](https://paulgo.io/search?q=jekyll%20custom%20functions&language=en-US&time_range=None&safesearch=1&categories=general) I dont get any LiveJournal results anymore; Closing.
