### ISSUE TITLE
Internal server Error when searching '\xa0'

### ISSUE THREAD

**Issue by ExTBH** [paulgoio/searxng#50]
website seems to crash when i try to search for `\xa0` or any search that contains it.

https://paulgo.io/search?q=%5Cxa0
https://paulgo.io/search?q=what+is+%5Cxa0

**Comment by dalf** [comment]
This is a SearXNG bug.

https://github.com/searxng/searxng/blob/675dc04917dadac60ebd4c28a1f5b1e2baba4cfa/searx/webutils.py#L153-L156

there are not raw strings

**Comment by ExTBH** [comment]
ahh, should i open an issue there or do they know about it and leaving it like this?

**Comment by mrpaulblack** [comment]
Hi,
sorry for the late reply. Issue seems to be fixed now upstream... Both links work. If the bgu still happens, please write a comments here in this issue ticket :+1: ; Closing.
