### ISSUE TITLE
Bug: google engine (HTTP 403 error)

### ISSUE THREAD

**Issue by cl0ck-byte** [paulgoio/searxng#53]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 2023.4.10+007bc732

**How did you install SearXNG?**

**What happened?**

403 errors, google does not return any searches

**How To Reproduce**

**Expected behavior**

service working

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.LocalProtocolError
  * Percentage: 0
  * Parameters: `(None, None, 'www.google.com')`
  * File name: `searx/search/processors/online.py:117`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'www.google.de')`
  * File name: `searx/search/processors/online.py:117`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:117`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:117`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'www.google.com')`
  * File name: `searx/search/processors/online.py:117`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi,
Sorry for the long wait. I finally reworked my proxy setup on the backend. Now the traffic of my instance is load balanced over multiple IPs on the backend again. These IPs should not be as easily blocked as before, since there are fewer requests per IP. Closing for now :+1:
