### ISSUE TITLE
Getting no results sometimes, and Google is suspended?

### ISSUE THREAD

**Issue by 100000BC** [paulgoio/searxng#54]
Hi!
I've been using your Searx instance and today I've had a few searches that just didn't bring up any results at all. I saw this little tab on the right side and spilled it open and this is what it said:

![image](https://github.com/paulgoio/searxng/assets/67931296/4b09a0f2-e6ec-4b42-a7b5-d8fb7b63b760)

Error! Engines cannot retrieve results: google ( [Suspended: access denied](https://paulgo.io/stats?engine=google) )

Not sure what the deal is, but I have really liked using your instance for the past few months.

**Comment by ChthonVII** [comment]
Ditto here. Probably some hostile action on Google's part.

**Comment by mrpaulblack** [comment]
Hi,
Thanks for the info. Currently, a lot of public instances have a problem with the Google engine. For example here: https://github.com/searxng/searxng/issues/2750. If we are lucky they are going to find a workaround upstream, otherwise Google is going to be not available all the time... Sorry :/

**Comment by return42** [comment]
@mrpaulblack did you activated the [link_token method](https://github.com/searxng/searxng/issues/2498#issuecomment-1590625541)?

**Comment by mrpaulblack** [comment]
No, I just enabled `link_token` in b0151ddb7d4b4387824b9169168a99c72e72a3a7 . Let's see if it helps on my instance. Thanks for pointing out :+1:

**Comment by return42** [comment]
.. and google [works again](https://paulgo.io/stats?engine=google) :)

.. don't worry about the "Errors and exceptions"  / look at the "Reliability".

**Comment by mrpaulblack** [comment]
I just deployed upstream commit `7dfcc3386e6787fe2267ae667fefff51cc4286a6` and set the suspension time for `SearxEngineAccessDenied` from 1 day to 60 seconds. I also enabled link_token to filter bot requests on the long run in the limiter. Google works for now again on my instance, thanks for the help Markus :+1: ; Closing.
