### ISSUE TITLE
images do not load

### ISSUE THREAD

**Issue by ac615223s5** [paulgoio/searxng#58]
![image](https://github.com/paulgoio/searxng/assets/33037196/96f2a99b-b07e-4af6-9581-aa91b71ec674)

```
Content-Security-Policy: The page’s settings blocked the loading of a resource (img-src) at https://plus.unsplash.com/premium_photo-1661918785181-378c2e53cb42?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.0.3&q=80&w=200 because it violates the following directive: “img-src 'self' data: https://*.tile.openstreetmap.org”
```

On firefox

**Comment by vojkovic** [comment]
Enable the image proxy under Preferences > Privacy > Image Proxy

**Comment by mrpaulblack** [comment]
Hi,
Sorry I was on vacation, thanks for the explanation vojkovic. Because of my CSP its only possible to use the image proxy through my instance for pictures :+1:
