### ISSUE TITLE
"Document Expired" when going back to search results page

### ISSUE THREAD

**Issue by p0arc** [paulgoio/searxng#60]
I use Firefox, when I click the back button after opening a website from the search results page, I should be able to get back there directly but instead I get the "Document Expired" page with this text showing when clicking Try Again button "To display this page, Firefox must send information that will repeat any action (such as a search or order confirmation) that was performed earlier.". It is not good to have to do two clicks before actually getting my results list page.

I didn't change any settings in SearXNG except for enabling Strict search. I, of course, use opnxng.com and this doesn't happen with other instances. 

If you want a picture of the Document Expired page for reference, I will upload it. I used opnxng instance for at least 8 months and it is been a great experience so far except for this problem.

**Comment by vojkovic** [comment]
Change your HTTP Method to 'GET' instead of 'POST' in `Preferences > Privacy > HTTP Method` and this shouldn't happen anymore. 👍

**Comment by p0arc** [comment]
Thank you so much! Everything is works well now. It's up to the maintainer whether he will close this issue or not cause right now I am not sure if this is a bug or a privacy feature to prevent requesting results from engines multiple times.

**Comment by mrpaulblack** [comment]
hmm I agree with vojkovic, this should not happen with GET method. I will close the issue, but if you find steps to repro this issue with the GET method, please let me know :+1:
