### ISSUE TITLE
Images look wonky

### ISSUE THREAD

**Issue by dsaderholm** [paulgoio/searxng#62]
Images are all the same size and arranged in one column. This is also happening on my own self-hosted instance.
![image](https://github.com/user-attachments/assets/401e7783-2aac-4350-b9e5-aa558689fd71)

**Comment by vojkovic** [comment]
Was fixed in https://github.com/searxng/searxng/pull/3921. Paul just needs to rebuild the css.

**Comment by mrpaulblack** [comment]
Hi,
I should have tested my instance better and missed this in my last prod deployment. Sorry about the inconvenience.

Also thanks for your quick response here Brock :+1: 

I pulled latest version from upstream and this is now fixed on my instance as well; Closing.

The same issue still persists on mobile layout tho (when width smaller 50em); I will open a quick PR upstream for that :+1:
